// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRytgKv6c6Ytt85eCpF4OaRZy0fcaDeXo',
    appId: '1:705656192509:web:512164ff2442c913b02d94',
    messagingSenderId: '705656192509',
    projectId: 'via-music-d4c27',
    authDomain: 'via-music-d4c27.firebaseapp.com',
    storageBucket: 'via-music-d4c27.firebasestorage.app',
    measurementId: 'G-EKMXNJ9ZBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDng0lNJN_7MyOuTkYHCIYH-fqx7Ddp_bQ',
    appId: '1:705656192509:android:2ffa634962cd62f3b02d94',
    messagingSenderId: '705656192509',
    projectId: 'via-music-d4c27',
    storageBucket: 'via-music-d4c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Bn3FelPwihl4g8OPzhzgTFEQFNilDHE',
    appId: '1:705656192509:ios:106ce846abbc0ad2b02d94',
    messagingSenderId: '705656192509',
    projectId: 'via-music-d4c27',
    storageBucket: 'via-music-d4c27.firebasestorage.app',
    androidClientId: '705656192509-1iulckperi1g2fr5ki9ssv4smop1gm9o.apps.googleusercontent.com',
    iosClientId: '705656192509-hcic6kcjjpsqqduq688p17tilbmt8oco.apps.googleusercontent.com',
    iosBundleId: 'com.rh.joytune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Bn3FelPwihl4g8OPzhzgTFEQFNilDHE',
    appId: '1:705656192509:ios:106ce846abbc0ad2b02d94',
    messagingSenderId: '705656192509',
    projectId: 'via-music-d4c27',
    storageBucket: 'via-music-d4c27.firebasestorage.app',
    androidClientId: '705656192509-1iulckperi1g2fr5ki9ssv4smop1gm9o.apps.googleusercontent.com',
    iosClientId: '705656192509-hcic6kcjjpsqqduq688p17tilbmt8oco.apps.googleusercontent.com',
    iosBundleId: 'com.rh.joytune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRytgKv6c6Ytt85eCpF4OaRZy0fcaDeXo',
    appId: '1:705656192509:web:a55b139c628a0b53b02d94',
    messagingSenderId: '705656192509',
    projectId: 'via-music-d4c27',
    authDomain: 'via-music-d4c27.firebaseapp.com',
    storageBucket: 'via-music-d4c27.firebasestorage.app',
    measurementId: 'G-4CM8K1JMM7',
  );
}
